name: isicle-docs
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - ipython
  - joblib
  - nbsphinx
  - numpy >=1.19.4
  - openbabel >=3.0.0
  - pandas >=1.1.4
  - python =3.9
  - rdkit <=2022.09.1
  - snakemake >=6.3.0
  - sphinx >= 3
  - sphinxcontrib-napoleon
  - sphinx_rtd_theme
  - statsmodels >=0.11.1
