adducts:
  ion_list: ['H-']
  element_list: ['O']
  method: 'explicit'
  save: True
md:
  forcefield: 'gff'
  energywindow: 6
  task: 'conformer'
  threads: 1
dft:
  tasks: ['optimize']
  functional: ['b3lyp']
  basis_set: ['6-31g*']
  ao_basis: 'cartesian'
  frequency: True
  atoms: ['H', 'C', 'F', 'P', 'O', 'N']
  temp: 298.15
  cosmo: False
  solvent: 'chcl3'
  gas: True
  max_iter: 150
  mem_global: 1600
  mem_heap: 100
  mem_stack: 600
  scratch_dir: '/scratch'
  command: 'csh /people/jyst649/opt/nwchem/nwchem-dec'
mobility:
  lennard_jones: 'default'
  i2: 5013489
  buffer_gas: 'nitrogen'
  buffer_gas_mass: 28.014
  temp: 300
  ipr: 1000
  itn: 10
  inp: 48
  imp: 1024
  command: '/people/dbaxter/deception/mobcal/mobcal_shm'
