{% set data = load_setup_py_data(setup_file='../setup.py',
                                 from_recipe_dir=True) %}

package:
  name: isicle
  version: {{ data.get('version') }}

source:
  path: ..

extra:
  channels:
    - conda-forge
    - bioconda
    - smcolby
    - anaconda

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - crest >=2.12
    - joblib
    - mobcal-shm
    - numpy >=1.19.4
    - nwchem >=7.0.2
    - openbabel >=3.0.0
    - openmpi
    - pandas >=1.1.4
    - python =3.9
    - rdkit >=2019
    - snakemake >=6.3.0
    - statsmodels >=0.11.1
    - xtb >=6.5.1

test:
  imports:
    - isicle
