{% set data = load_setup_py_data(setup_file='../setup.py',
                                 from_recipe_dir=True) %}

package:
  name: isicle
  version: {{ data.get('version') }}

source:
  path: ..

extra:
  channels:
    - conda-forge
    - bioconda

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7,<3.10
    - pip
  run:
    - numpy >=1.19.4
    - openbabel >=3.0.0
    - pandas >=1.1.4
    - python >=3.7,<3.10
    - rdkit >=2019
    - snakemake >=6.3.0
    - statsmodels >=0.11.1
    - xtb
    - crest
    - nwchem

test:
  imports:
    - isicle
