{% set data = load_setup_py_data(setup_file='../setup.py',
                                 from_recipe_dir=True) %}

package:
  name: isicle
  version: {{ data.get('version') }}

source:
  path: ..

extra:
  channels:
    - conda-forge
    - bioconda

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - numpy
    - pandas
    - python >=3.7
    - rdkit
    - snakemake
    - statsmodels

test:
  imports:
    - isicle
